// src/app/terms-of-service-medichy/page.jsx
import React from 'react';

export default function MedichyTermsOfServicePage() {
  // תאריך היום משמש כתאריך התחולה
  const effectiveDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="bg-white text-gray-800 font-sans antialiased">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="max-w-4xl mx-auto">
          
          <header className="text-center mb-10 border-b border-gray-200 pb-4">
            <h1 className="text-4xl font-extrabold text-gray-900">Terms of Service — Medichy</h1>
            <p className="text-gray-500 mt-2">Effective date: {effectiveDate}</p>
          </header>

          <main className="prose prose-lg max-w-none prose-headings:text-gray-900 prose-p:text-gray-700 prose-li:text-gray-700">
            <p><strong>Owner/Provider:</strong> D&A Code Design (the “Company”)</p>
            <p><strong>Contact:</strong> <a href="mailto:support@medichy.app">support@medichy.app</a></p>

            <h2>1. Acceptance</h2>
            <p>By installing or using Medichy you agree to these Terms and to our Privacy Policy. If you do not agree, do not use the Service.</p>

            <h2>2. The Service</h2>
            <p>Medichy is an AI-powered platform that generates personalized meditation scripts and audio tracks. Based on user input (such as mood, goals, duration, and preferences), the app uses Artificial Intelligence and Text-to-Speech technologies to create unique wellness sessions.</p>

            <h2>3. Eligibility and Accounts</h2>
            <p>You must be at least 16 years old (or the age required by your local law) or have a parent/guardian’s consent. You are responsible for keeping your device and login secure and for all activity on your account.</p>

            <h2>4. Permissions and AI Usage</h2>
            <p>The app requires internet access to generate content via cloud-based AI services. You acknowledge that the content (text and audio) is generated by Artificial Intelligence and may vary in accuracy or tone. You are responsible for configuring your device to allow audio playback and notifications.</p>

            <h2>5. User Content & Public Sharing</h2>
            <p>You retain ownership of the personal inputs you provide. However:</p>
            <ul>
                <li><strong>License:</strong> You grant the Company a license to process your inputs to generate the meditation sessions.</li>
                <li><strong>Public Wall:</strong> If you choose to share your created sessions on the "Public Wall" or via other sharing features, you grant us a license to display, distribute, and allow other users to listen to that content publicly.</li>
            </ul>
            
            <h2>6. Prohibited Use</h2>
            <p>Do not use the Service to: generate harmful, abusive, or illegal content; reverse-engineer the AI models; bypass security; or interfere with the Service or networks.</p>

            <h2>7. Medical & Health Disclaimer</h2>
            <p><strong>Medichy is a relaxation and wellness tool, NOT a medical device.</strong></p>
            <p>The content provided by the app is for general information and entertainment purposes only. It is not intended to diagnose, treat, cure, or prevent any disease or medical condition. Do not rely on Medichy for psychological or psychiatric emergencies. If you have a health concern, consult a qualified healthcare professional.</p>

            <h2>8. Third-Party Services</h2>
            <p>We use reputable third parties to operate the Service, such as:</p>
            <ul>
              <li><strong>Firebase (Google):</strong> Hosting, storage, authentication, and database.</li>
              <li><strong>ElevenLabs / OpenAI:</strong> AI text generation and voice synthesis.</li>
              <li><strong>OneSignal:</strong> Push notifications.</li>
            </ul>
            <p>Your use of Medichy also constitutes acceptance of the applicable terms of such providers. We are not responsible for their acts, outages, or AI generation errors.</p>

            <h2>9. Privacy</h2>
            <p>How we collect, use, share, and retain data is described in the Medichy Privacy Policy. By using the Service you consent to those practices, including the processing of your inputs by AI providers.</p>

            <h2>10. Fees</h2>
            <p>We may offer free and/or paid features. We may change pricing or introduce fees with notice on the site/app. Taxes and carrier data charges are your responsibility.</p>
            
            <h2>11. Service Changes and Availability</h2>
            <p>We may modify, suspend, or discontinue the Service or any feature at any time, temporarily or permanently, without liability to you.</p>

            <h2>12. Intellectual Property</h2>
            <p>The Service, software, branding, and the AI generation methodology are owned by the Company and protected by IP laws. You receive a personal, non-exclusive, non-transferable, revocable license to use the app in accordance with these Terms.</p>
            
            <h2>13. Termination</h2>
            <p>You may stop using the Service at any time. We may suspend or terminate access immediately for any breach or suspected misuse. Upon termination, your license ends and certain provisions survive.</p>

            <h2>14. Disclaimers</h2>
            <p>THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED. We do not warrant that the AI-generated content will be accurate, suitable for your specific needs, or error-free.</p>

            <h2>15. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY SHALL NOT BE LIABLE FOR: (a) INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES; (b) PERSONAL INJURY OR EMOTIONAL DISTRESS ARISING FROM USE OF THE CONTENT; (c) DEVICE OR DATA ISSUES.</p>
            <p>Our total aggregate liability shall not exceed the greater of US$50 or the amount you paid to use the Service in the 12 months preceding the claim.</p>
            
            <h2>16. Indemnification</h2>
            <p>You agree to defend, indemnify, and hold the Company harmless from claims arising from your use of the Service, your shared content, or your breach of these Terms.</p>

            <h2>17. Account and Data Deletion</h2>
            <p>You may request deletion of your account and data by emailing <a href="mailto:support@medichy.app">support@medichy.app</a>. We may retain limited records as required by law.</p>

            <h2>18. Governing Law and Venue</h2>
            <p>These Terms are governed by the laws of the State of Israel. The exclusive jurisdiction and venue shall be the competent courts in Tel-Aviv–Jaffa, Israel.</p>

            <h2>19. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Material changes will be posted on the site/app with a revised Effective Date. Your continued use after changes becomes your acceptance of the updated Terms.</p>

            <h2>20. Miscellaneous</h2>
            <p>If any provision is found unenforceable, the remainder remains in effect. These Terms constitute the entire agreement between you and the Company regarding the Service.</p>
          </main>
        </div>
      </div>
    </div>
  );
}